## 5. <strong>NumPy 배열</strong>

In [14]:
# Python 패키지 설치 명령어
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [15]:
# NumPy 불러오기
import numpy as np

In [16]:
import sys

In [17]:
sys.getsizeof(100000000000000000)

32

### <strong> 5.1 NumPy 배열 생성

In [19]:
# [+] 리스트 객체로부터 ndarray 객체 생성
my_lst = [1,2,3,4,5,6]
my_arr = np.array(my_lst)
print(my_arr)

[1 2 3 4 5 6]


In [20]:
type(my_arr)

numpy.ndarray

In [27]:
# [+] 리스트/NumPy 배열 동시에 생성
np.array([1,3,4])

array([1, 3, 4])

#### 리스트 컴프리헨션 vs NumPy 배열

In [30]:
prices = [20, 40, 35, 10, 25, 56]
new_prices = [price-5 for price in prices]
# [+] 리스트 컴프리헨션을 이용하여 5달러씩 할인된 가격 리스트를 생성
print(new_prices)

# [+] NumPy 배열의 연산을 통한 5달러씩 할인된 가격 리스트를 생성
prices_arr = np.array(prices)
prices_arr -= 5
print(prices_arr)

[15, 35, 30, 5, 20, 51]
[15 35 30  5 20 51]


#### 예제: 시험 점수 처리

In [33]:
# 세 번의 시험에 대한 점수를 NumPy 배열로 선언
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

In [34]:
# [+] 세 번째 시험에 2점씩 더하기
test_3_fixed = test_3 + 2
print(test_3_fixed)

[89 87 74 92 94]


In [36]:
# [+] 학생 별 전체 시험 점수 총합 계산 -> total_grade
total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

[260 281 248 276 272]


In [38]:
# [+] 학생 별 평균 시험 점수 계산 -> final_grade
final_grade = total_grade / 3
print(final_grade)

[86.66666667 93.66666667 82.66666667 92.         90.66666667]


In [40]:
# [+] 인덱싱: Jeremy의 두 번째 시험 점수
jeremy_test_2 = test_2[3]
print(jeremy_test_2)

93


In [42]:
# [+] Manual과 Adwoa의 첫 번째 시험 점수
manual_adwoa_test_1 = test_1[1:3]
print(manual_adwoa_test_1)

[94 88]


In [44]:
# [+] 전체 학생들의 점수를 2차원 배열에 저장 -> student_scores
student_scores = np.array([test_1, test_2, test_3_fixed])
print(student_scores)

[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 89  87  74  92  94]]


In [46]:
# [+] 2차원 배열 인덱싱: Tanya의 세 번째 시험 점수
print(student_scores[2,0])

# [+] 2차원 배열 슬라이싱: Cody의 전체 시험 점수
print(student_scores[:, 4])

89
[87 91 94]


#### 배열 원소 단위의 논리 연산

In [50]:
a = np.array([1, 20, 4, 6, 28, 88, 7, 12])
mask = a>5
# [+] 150 이상 여부를 마스킹
...
print(mask)

[False  True False  True  True  True  True  True]


In [51]:
# [+] 논리 연산을 이용하여 부분집합 구하기
selected = a[a > 5]
print(selected)

[20  6 28 88  7 12]


In [52]:
# [+] 논리식 결합: 논리합
selected = a[(a < 20)|(a > 3)]
print(selected)

[ 1 20  4  6 28 88  7 12]


In [53]:
# [+] 논리식 결합: 논리곱
selected = a[(a > 10)&(a < 20)]
print(selected)

[12]


In [54]:
# [+] 정수 배열 생성
np.arange(20) # 0~19
np.arange(10,20) # 10~19
np.arange(10,20,3)


array([10, 13, 16, 19])

In [57]:
# [+] 난수 배열 생성

np.random.seed(5)
arr = np.random.randint(10, size=(3, 5))
print(arr)

[[3 6 6 0 9]
 [8 4 7 0 0]
 [7 1 5 7 0]]


In [62]:
# 실습 문제

In [64]:
porridge = np.array([50, 80, 62 ,77, 98, 76, 49, 68, 65])

In [66]:
cold = porridge[porridge < 60]
cold

array([50, 49])

In [67]:
hot = porridge[porridge > 80]
hot

array([98])

In [70]:
just_right = porridge[(porridge >= 60) & (porridge <= 80)]
just_right

array([80, 62, 77, 76, 68, 65])

### <strong>5.2 배열 조작 연산</strong>

In [110]:
arr = np.random.randint(10, size = (3, 5))
arr

array([[6, 4, 5, 2, 8],
       [8, 1, 6, 3, 4],
       [1, 8, 0, 2, 2]])

In [112]:
# [+] 배열 속성
print(arr.ndim)     # 차원 수
print(arr.shape)    # 형상
print(arr.size)     # 크기
print(arr.dtype)    # 데이터 타입
print(arr.itemsize) # 원소별 메모리 크기(bytes)
print(arr.nbytes)   # 전체 메모리 크기

2
(3, 5)
15
int64
8
120


In [116]:
# [+] 배열 슬라이싱
arr = np.arange(10)
print(arr)
print(arr[3:7])
print(arr[:5])
print(arr[5:])
print(arr[::3])
print(arr[2:8:2])


[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [124]:
np.random.seed(0)
arr = np.random.randint(10, size=(6, 8))
arr

array([[5, 0, 3, 3, 7, 9, 3, 5],
       [2, 4, 7, 6, 8, 8, 1, 6],
       [7, 7, 8, 1, 5, 9, 8, 9],
       [4, 3, 0, 3, 5, 0, 2, 3],
       [8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7]])

In [128]:
# [+] 다차원 배열 슬라이싱
arr[3:5, 4:7]

array([[5, 0, 2],
       [3, 7, 0]])

In [132]:
np.random.seed(0)
arr = np.random.randint(10, size=(3, 4))
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [ ]:
#실습 문제

In [169]:
np.random.seed(0)
arr = np.random.randint(10, size=(5, 8))
print(arr)

[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]]


In [165]:
arr[:2,:3]
arr[:3,::2]

array([[5, 3, 7, 3],
       [2, 7, 8, 1],
       [7, 8, 5, 8]])

In [171]:
# 배열 슬라이스 = 뷰(view)
arr_sub = arr[:2, :2]
print(arr_sub)

arr_sub[0, 0] = 99
print(arr_sub)

print(arr)

[[5 0]
 [2 4]]
[[99  0]
 [ 2  4]]
[[99  0  3  3  7  9  3  5]
 [ 2  4  7  6  8  8  1  6]
 [ 7  7  8  1  5  9  8  9]
 [ 4  3  0  3  5  0  2  3]
 [ 8  1  3  3  3  7  0  1]]


In [173]:
# .copy()
arr_sub = arr[:2, :2].copy()

arr_sub[0, 0] = 99
print(arr_sub)

print(arr)

[[99  0]
 [ 2  4]]
[[99  0  3  3  7  9  3  5]
 [ 2  4  7  6  8  8  1  6]
 [ 7  7  8  1  5  9  8  9]
 [ 4  3  0  3  5  0  2  3]
 [ 8  1  3  3  3  7  0  1]]


In [181]:
x = np.arange(10)
print(x, '\n')

[0 1 2 3 4 5 6 7 8 9] 



In [203]:
# [+] 배열 재구조화: reshape()
x.reshape(2,5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [207]:
arr = np.ones((3, 4))
print(arr)
print(arr.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)


In [215]:
# [+] 배열 재구조화: 차원 추가(np.newaxis)
arr_new = arr[np.newaxis, :,:]
print(arr_new)
print(arr_new.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(1, 3, 4)


In [217]:
arr_new = arr[:,:,np.newaxis]
print(arr_new)
print(arr_new.shape)

[[[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]]
(3, 4, 1)


In [219]:
arr_1 = np.arange(1, 4)
arr_2 = np.arange(4, 7)
arr_3 = np.arange(7, 10)

print(arr_1, arr_2, arr_3)

[1 2 3] [4 5 6] [7 8 9]


In [229]:
# [+] 배열 연결: np.concatenate()
arr_total = np.concatenate([arr_1, arr_2, arr_3])
print(arr_total)

[1 2 3 4 5 6 7 8 9]


In [231]:
# [+] 배열 연결: 종연결 
arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [235]:
# [+] 배열 연결: 횡연결
arr_total = np.hstack([arr_1, arr_2, arr_3])
print(arr_total)

[1 2 3 4 5 6 7 8 9]


In [237]:
arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr)

[1, 2, 3, 99, 99, 3, 2, 1]


In [239]:
# [+] 배열 분할
arr_1, arr_2, arr_3 = np.split(arr,[3,5])
print(arr_1, arr_2, arr_3)

[1 2 3] [99 99] [3 2 1]
