## <strong>6. NumPy: Universal Functions (UFunc)</strong>

In [12]:
import numpy as np

In [13]:
# 역수 계산 함수
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

# 함수 테스트
values = np.random.randint(1, 10, size=5)
print(values)
print(compute_reciprocals(values))

[2 1 5 7 6]
[0.5        1.         0.2        0.14285714 0.16666667]


#### 역수 계산: Python loop vs NumPy ufuncs
+ ```%timeit```: 셀 단위 코드 실행 시간을 측정하는 매직 함수

In [15]:
# 백만 개 크기의 난수 배열 생성
big_array = np.random.randint(1, 100, size=1000000)

In [16]:
# [+] Python loop를 통한 역수 계산
%timeit compute_reciprocals(big_array) 

1.98 s ± 48.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [21]:
# NumPy ufunc을 통한 벡터화된 역수 계산
%timeit 1 / big_array

1.52 ms ± 26.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


#### UFuncs: 유연한 연산 제공

In [27]:
# 난수 배열 2개 생성
np.random.seed(1)
arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)

print(arr1, arr2)

[5 8 9 5 0] [0 1 7 6 9]


In [29]:
# 배열-스칼라 연산
arr1 = arr1 - 2
print(arr1)

[ 3  6  7  3 -2]


In [31]:
# 배열-배열 연산
arr3 = arr1 + arr2
print(arr3)

[ 3  7 14  9  7]


In [40]:
# 다차원 배열 연산: 2차원 배열 ** 스칼라
arr4 = np.random.randint(10, size=(3, 5))
print(arr4)

arr5 = arr4 ** 2
print(arr5)

[[9 7 6 9 1]
 [0 1 8 8 3]
 [9 8 7 3 6]]
[[81 49 36 81  1]
 [ 0  1 64 64  9]
 [81 64 49  9 36]]


In [42]:
"""
    UFuncs: 산술 연산
"""

# Basic arithmetic operations on an array
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x ** 2 =", x ** 2)

# [+] 산술 연산에 대응하는 유니버설 함수
print("x + 5 =", np.add(x,5)
print("x - 5 =", np.add(x,5))
print("x * 2 =", np.add(x,5))
print("x / 2 =", np.add(x,5))
print("x ** 2 =", np.add(x,5))


SyntaxError: invalid syntax (1366319824.py, line 16)

In [45]:
"""
    UFuncs: 절댓값 계산
"""

# 절댓값 함수
x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

# 복소수에 대한 절댓값 계산
x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [51]:
"""
    np.linspace(start, stop, num): 선형 간격 벡터 생성
        - start: 벡터의 시작 값
        - end: 벡터의 종료 값
        - num: 생성할 값의 개수
"""

# [+][0, 100]의 범위를 가지며, 균일한 간격의 5개의 값들로 구성되는 벡터를 생성
x = np.linspace(0, 100, 5)
print(x)

[  0.  25.  50.  75. 100.]


In [55]:
# [+] [0, 100]의 범위를 가지며, [0, 10, 20, 30, ..., 100]와
# 같은 값들로 구성되는 벡터를 생성
x = np.linspace(0, 100, 11)
print(x)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [ ]:
# 삼각함수(trigonometric functions)
theta = np.linspace(0, np.pi, 3)

print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

In [59]:
"""
    집계 함수: reduce()
"""

# 배열 생성
x = np.arange(1, 5)
print(x)

[1 2 3 4]


In [62]:
# [+] 덧셈 연산으로 집계
aggr = np.add.accumulate(x)
print(aggr)

[ 1  3  6 10]


In [64]:
# [+] 곱셈 연산으로 집계
aggr = np.multiply.accumulate(x)
print(aggr)

[ 1  2  6 24]


In [ ]:
"""
    집계 함수: accumulate()
"""

# [+] 덧셈 연산으로 집계
accum = ...
print(accum)

In [ ]:
# [+] 곱셈 연산으로 집계
accum = ...
print(accum)

In [ ]:
# 집계 함수: sum()
np.random.seed(3)
arr = np.random.rand(1000000) # rand(): 0~1 사이의 실수 형태의 난수 배열 생성

print(arr)
print("sum =", np.sum(arr))

In [ ]:
# sum(): Python 내장함수
%timeit sum(arr)

In [ ]:
# np.sum()
%timeit np.sum(arr) # 1000µs = 1ms

In [ ]:
# [+] 그 외의 집계함수
print("max =", ...)
print("min =", ...)
print("mean =", ...)
print("median =", ...)
print("percentile =", ...)
print("variance =", ...)
print("standard deviation =", ...)
print("index of maximum value =", ...)
print("index of minimum value =", ...)
print("Is there any number greater than 1? =", ...)
print("Is every number greater than 0? =", ...) 

In [ ]:
# 다차원 집계
np.random.seed(0)
arr = np.random.randint(10, size=(3, 4))
print(arr, '\n')

print(np.sum(arr, axis=0), '\n')
print(np.sum(arr, axis=1))