## <strong> 8. Pandas 객체 생성 및 조작 </strong>

```Pandas``` 라이브러리 설치

In [29]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [30]:
import pandas as pd
import numpy as np

In [31]:
# 헬프 문서 출력
pd?

Type:        module
String form: <module 'pandas' from '/opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages/pandas/__init__.py'>
File:        /opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages/pandas/__init__.py
Docstring:  
pandas - a powerful data analysis and manipulation library for Python

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.

In [32]:
# 라이브러리 버전 확인
pd.__version__

'1.4.2'

### Pandas 객체: <strong> Series </strong>

In [34]:
# [+] List 객체에서 Series 객체를 생성
ser = pd.Series([0.25, 0.5, 0.75, 1.0])
ser

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [35]:
# Pandas 객체 속성: .values
vals = ser.values
vals

array([0.25, 0.5 , 0.75, 1.  ])

In [36]:
# Pandas 객체 속성: .index
ind = ser.index
print(ind)
print(list(ind))

RangeIndex(start=0, stop=4, step=1)
[0, 1, 2, 3]


In [37]:
# [+] 레이블 기반 인덱싱
ser = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c','d'])
print(ser)
print(ser['a'])
print(ser[0])

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.25
0.25


### <strong> Dictionary와 Series 객체 </strong>

In [39]:
# Dictionary 객체에서 Series 객체를 생성
population_dict = {
    'California': 38332521,   # 미국 연방주 별 인구
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135
}

population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [40]:
population['Texas' : 'Florida']

Texas       26448193
New York    19651127
Florida     19552860
dtype: int64

In [41]:
# [+] 레이블 기반 인덱싱: 'California'에서 'New York'까지
population['California' : 'New York']

California    38332521
Texas         26448193
New York      19651127
dtype: int64

### Pandas 객체:<strong> DataFrame </strong>

In [43]:
# 미국 연방주 별 면적
area_dict = {
    'California': 423967,
    'Texas': 695662,
    'New York': 141297,
    'Florida': 170312,
    'Illinois': 149995
}

area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [44]:
# [+] 'population'과 'area' Series 객체를 포함하는 DataFrame 객체 생성
states = pd.DataFrame({'population':population,'area':area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [45]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [46]:
# DataFrame 객체의 인덱스와 컬럼
print(states.index)
print(states.columns)

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Index(['population', 'area'], dtype='object')


In [47]:
# [+] DataFrame으로부터 Series 객체 접근하기
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

#### NumPy 배열로부터 DataFrame 객체 생성
+ 예제, 오늘의 운세: 금전운(```money_fortune```), 연애운(```love_fortune```)

In [49]:
# [+] 실수 난수로 이루어진 12X2 크기의 NumPy 배열 생성
arr = np.random.rand(12, 2)
arr

array([[0.34275051, 0.01514987],
       [0.12563304, 0.0051739 ],
       [0.21007674, 0.75692351],
       [0.82158315, 0.50550822],
       [0.692705  , 0.414291  ],
       [0.95667885, 0.27957336],
       [0.69220011, 0.01374035],
       [0.19614291, 0.23384929],
       [0.68134118, 0.65449021],
       [0.58482971, 0.36348757],
       [0.18607437, 0.34729394],
       [0.4672086 , 0.93416899]])

In [50]:
# NumPy 배열로부터 DataFrame 객체 생성
df = pd.DataFrame(
    arr, 
    columns=['money_fortune', 'love_fortune'], 
    index=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
)

df

money_fortune  love_fortune
Jan       0.342751      0.015150
Feb       0.125633      0.005174
Mar       0.210077      0.756924
Apr       0.821583      0.505508
May       0.692705      0.414291
Jun       0.956679      0.279573
Jul       0.692200      0.013740
Aug       0.196143      0.233849
Sep       0.681341      0.654490
Oct       0.584830      0.363488
Nov       0.186074      0.347294
Dec       0.467209      0.934169

### <strong> Series 객체 조작 </strong>

#### Dictionary 스타일 조작

In [53]:
# Series 객체 생성
ser = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])

print(ser)    
print('a' in ser)   # [+] Key + in 키워드
print(0.25 in ser)  # [+] Value + in 키워드
print(ser.index)    # [+] 인덱스
print(ser.keys())   # [+] 키 집합
ser['e'] = 1.25     # [+] 값 추가
ser['a'] = 100    # [+] 값 수정
print(ser)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
True
False
Index(['a', 'b', 'c', 'd'], dtype='object')
Index(['a', 'b', 'c', 'd'], dtype='object')
a    100.00
b      0.50
c      0.75
d      1.00
e      1.25
dtype: float64


#### 배열 스타일 조작

In [55]:
print(ser['a':'c'])   # 슬라이싱
print(ser[(ser > 0.3) & (ser < 0.8)])   # 논리 연산
# 팬시 인덱싱
ind = ['a', 'e'] 
print(ser[ind])

a    100.00
b      0.50
c      0.75
dtype: float64
b    0.50
c    0.75
dtype: float64
a    100.00
e      1.25
dtype: float64


#### Pandas 객체 인덱싱
+ 정수 기반 인덱싱(암묵적, implicit)
+ 레이블 기반 인덱싱(명시적, explicit)

In [57]:
# 슬라이싱을 이용한 'a', 'b', 'c' 선택
print(ser[0:3])   # 정수 기반 인덱싱
print(ser['a':'c'])     # 레이블 기반 인덱싱

a    100.00
b      0.50
c      0.75
dtype: float64
a    100.00
b      0.50
c      0.75
dtype: float64


### <strong> DataFrame 객체 조작 </strong>

In [59]:
# 특정 Series 객체 접근
states['area']
states.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [60]:
# [+] Series 객체 추가 (밀도 = 인구 / 면적)
states['density'] = states['population'] / states['area']
states

population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

#### 인덱서: ```loc```, ```iloc```

In [86]:
# Series 객체 생성
ser = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
ser

1    a
3    b
5    c
dtype: object

In [115]:
# loc 인덱서
print(ser.loc[1])
print(ser.loc[1:3])

a
1    a
3    b
dtype: object


In [116]:
# iloc 인덱서
print(ser.iloc[1])
print(ser.iloc[1:3])

b
3    b
5    c
dtype: object


In [118]:
# DataFrame 객체 = 2차원 배열
print(states.values, '\n')        # 값들을 얻어오기
print(states.T, '\n')             # 전치행렬
print(states.iloc[:3, :2], '\n')  # 정수 기반 슬라이싱
print(states.loc[: 'Illinois', : 'population'])  # 레이블 기반 슬라이싱

[[3.83325210e+07 4.23967000e+05 9.00000000e+01]
 [2.64481930e+07 6.95662000e+05 3.80187404e+01]
 [1.96511270e+07 1.41297000e+05 1.39076746e+02]
 [1.95528600e+07 1.70312000e+05 1.14806121e+02]
 [1.28821350e+07 1.49995000e+05 8.58837628e+01]] 

            California         Texas      New York       Florida      Illinois
population  38332521.0  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
area          423967.0  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
density           90.0  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01 

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297 

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135


In [119]:
# 마스킹 + 팬시 인덱싱
states.loc[states.density > 100, ['population', 'density']]

population     density
New York    19651127  139.076746
Florida     19552860  114.806121

In [67]:
# 값 수정
states.iloc[0, 2] = 90
states

population    area     density
California    38332521  423967   90.000000
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763